Repository jenkinsci/acceptance-test-harness, pull requests merged in 2021-02, with the labels that each got.

#635 Delete publish-*-plugin tests
  src/main/java/org/jenkinsci/test/acceptance/plugins/publish_over/FtpGlobalConfig.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/publish_over/FtpPublisher.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/publish_over/PublishOverSSHGlobalConfig.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/publish_over/PublishOverSSHPublisher.java
  src/test/java/plugins/FtpPublishPluginTest.java
  src/test/java/plugins/PublishOverSSHPluginTest.java
  src/test/resources/ftp_plugin/flat/odes.txt
  src/test/resources/ftp_plugin/odes.txt
  src/test/resources/ftp_plugin/old.txt
  src/test/resources/ftp_plugin/prefix_/.exclude
  src/test/resources/ftp_plugin/prefix_/test.txt
  src/test/resources/ftp_plugin/te,st.txt
Labels: fix

#634 Delete plot-plugin tests
  src/main/java/org/jenkinsci/test/acceptance/plugins/plot/CsvDataSeries.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/plot/DataSeries.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/plot/Plot.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/plot/PlotPublisher.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/plot/PropertiesDataSeries.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/plot/XmlDataSeries.java
  src/test/java/plugins/plot/PlotPluginPropertiesTest.java
  src/test/java/plugins/plot/PlotPluginTest.java
  src/test/java/plugins/plot/PlotPluginXmlTest.java
  src/test/resources/plot_plugin/plot.csv
  src/test/resources/plot_plugin/plot.properties
  src/test/resources/plot_plugin/plot.xml
  src/test/resources/plot_plugin/plot_with_strings.csv
Labels: fix

#639 Delete mission-control plugin tests.
  src/main/java/org/jenkinsci/test/acceptance/plugins/mission_control/BuildHistoryArea.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/mission_control/BuildQueueArea.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/mission_control/JobStatusArea.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/mission_control/MissionControlView.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/mission_control/NodeStatusArea.java
  src/test/java/plugins/MissionControlTest.java
Labels: fix

#636 MockUpdateCenter should only be installed if the current UC is the default
  src/main/java/org/jenkinsci/test/acceptance/update_center/MockUpdateCenter.java
Labels: bug

#637 failure stacktrace is no longer trimmed by surefire
  pom.xml
Labels: enhancement

#641 Delete CIFS publisher plugin tests
  src/main/java/org/jenkinsci/test/acceptance/plugins/publish_over/CifsGlobalConfig.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/publish_over/CifsPublisher.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/publish_over/PublishGlobalConfig.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/publish_over/PublishGlobalPublisher.java
  src/test/java/plugins/CIFSPublishPluginTest.java
  src/test/java/plugins/GlobalPublishPluginTest.java
Labels: fix

#643 reduce flakiness of doSuccesfulLogin
  src/main/java/org/jenkinsci/test/acceptance/po/Login.java
  src/test/java/plugins/ActiveDirectoryTest.java
Labels: fix

#646 Fix form validation
  src/main/java/org/jenkinsci/test/acceptance/po/FormValidation.java
Labels: fix
