Repository jenkinsci/acceptance-test-harness, pull requests merged in 2021-03, with the labels that each got.

#645 Fix driver location support when run on windows and cygwin is in the path.
  src/main/java/org/jenkinsci/test/acceptance/FallbackConfig.java
Labels: fix

#647 [JENKINS-65016] ignore failures from buggy firefox
  src/test/java/core/FormValidationTest.java
Labels: internal

#648 Allow the firefox binary to be specified with `FIREFOX_BIN`
  docs/BROWSER.md
  src/main/java/org/jenkinsci/test/acceptance/FallbackConfig.java
Labels: enhancement

#649 Add the ability to connect to a remote chrome session with `BROWSER=remote-webdriver-chrome`
  docs/BROWSER.md
  src/main/java/org/jenkinsci/test/acceptance/FallbackConfig.java
Labels: enhancement

#642 Attach support bundle after running the test
  README.md
  docs/SUPPORT-BUNDLE.md
  pom.xml
  src/main/java/org/jenkinsci/test/acceptance/junit/AbstractJUnitTest.java
  src/main/java/org/jenkinsci/test/acceptance/po/Jenkins.java
  src/main/java/org/jenkinsci/test/acceptance/recorder/SupportBundle.java
  src/main/java/org/jenkinsci/test/acceptance/utils/SupportBundleRequest.java
Labels: enhancement

#651 update form-element-path to prevent some detached plugins
  src/main/java/org/jenkinsci/test/acceptance/FallbackConfig.java
Labels: internal
