Repository jenkinsci/acceptance-test-harness, pull requests merged in 2021-10, with the labels that each got.

#689 Change envVarOpts to protected for use in derived class
  src/main/java/org/jenkinsci/test/acceptance/controller/WinstoneController.java
Labels: enhancement

#692 Fix MatrixPluginTest#run_configurations_on_with_a_given_label for Jenkins 2.307+
  src/test/java/plugins/MatrixPluginTest.java
Labels: bug

#693 Fix selector for test result trend
  src/test/java/plugins/XUnitPluginTest.java
Labels: bug

#695 Fix PrioritySorterPluginTest tests
  src/main/java/org/jenkinsci/test/acceptance/plugins/priority_sorter/PriorityConfig.java
  src/main/java/org/jenkinsci/test/acceptance/po/Slave.java
Labels: bug

#696 Fix JobDslPluginTest#are_columns_created
  src/main/java/org/jenkinsci/test/acceptance/po/View.java
  src/test/java/plugins/JobDslPluginTest.java
Labels: bug

#694 Fix OwnershipPluginTest#correct_redirect_after_save
  src/test/java/plugins/OwnershipPluginTest.java
Labels: bug

#698 [JENKINS-66827] enable the ability to specify the proxy server
  docs/BROWSER.md
  src/main/java/org/jenkinsci/test/acceptance/FallbackConfig.java
  src/main/java/org/jenkinsci/test/acceptance/recorder/HarRecorder.java
  src/test/java/org/jenkinsci/test/acceptance/recorder/HarRecorderTest.java
Labels: fix

#669 Fix the NodeLabelParameterPluginTests
  src/main/java/org/jenkinsci/test/acceptance/plugins/nodelabelparameter/LabelParameter.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/nodelabelparameter/NodeParameter.java
  src/main/java/org/jenkinsci/test/acceptance/po/BuildHistory.java
  src/main/java/org/jenkinsci/test/acceptance/po/Job.java
  src/test/java/plugins/NodeLabelParameterPluginTest.java
Labels: fix
