Repository jenkinsci/acceptance-test-harness, pull requests merged in 2022-09, with the labels that each got.

#910 replace msbuild with junit in InstallWizardTest
  src/test/java/core/InstallWizardTest.java
Labels: chore

#868 Adapt changes to breadcrumbs accessibility
  src/main/java/org/jenkinsci/test/acceptance/plugins/dashboard_view/read/BreadCrumbs.java
Labels: enhancement

#905 chore(ATH Docker Image) build and deploy with infra.ci.jenkins.io
  Jenkinsfile.infra.ci.jenkins.io
  src/main/resources/ath-container/Dockerfile
Labels: chore

#917 Add docker badge to README
  README.md
Labels: documentation

#915 Fix plugin size mismatch when LOCAL_JARS is used
  src/main/java/org/jenkinsci/test/acceptance/update_center/MockUpdateCenter.java
Labels: bug

#928 Fix byte-buddy dependabot exclusion
  .github/dependabot.yml
Labels: chore

#932 Remove obsolete Java mail dependency
  pom.xml
Labels: dependencies

#931 Replace slf4j-log4j12 with slf4j-jdk14
  pom.xml
Labels: dependencies

#934 Drop XMLUnit-legacy
  pom.xml
Labels: dependencies

#940 Bump maven from 3.8.3 to 3.8.6 for the Dockerfile
  src/main/resources/ath-container/Dockerfile
Labels: dependencies

#937 Update trilead-ssh from build212-hudson-6 to build-217-jenkins-223.v546f979619d4
  pom.xml
Labels: dependencies

#936 Drop obsolete javax.inject dependency
  pom.xml
Labels: dependencies

#929 Remove obsolete process-utils dependency
  pom.xml
Labels: dependencies

#938 Update commons-configuration to 2.x
  pom.xml
  src/main/java/org/jenkinsci/test/acceptance/utils/pluginreporter/TextFileExercisedPluginReporter.java
Labels: dependencies

#930 Remove Java 8 restrictions and use Java 11
  pom.xml
  src/main/resources/ath-container/Dockerfile
  src/main/resources/ath-container/set-java.sh
Labels: breaking

#948 Update trilead-ssh from build-217-jenkins-223.v546f979619d4 to build-217-jenkins-231.vda_87ca_d57ecf
  pom.xml
Labels: dependencies

#950 Drop obsolete commons-codec dependency
  pom.xml
Labels: dependencies

#954 Escape maven version in Dockerfile
  src/main/resources/ath-container/Dockerfile
Labels: bug

#949 Update htmlunit-driver from 2.33.0 to 2.64.0
  pom.xml
Labels: dependencies
