Repository jenkinsci/acceptance-test-harness, pull requests merged in 2022-08, with the labels that each got.

#886 Use "No verification" ssh host key verification strategy
  src/main/java/org/jenkinsci/test/acceptance/plugins/git_client/ssh_host_key_verification/AcceptFirstConnectionStrategy.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/git_client/ssh_host_key_verification/KnownHostsFileStrategy.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/git_client/ssh_host_key_verification/ManuallyProvidedKeysStrategy.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/git_client/ssh_host_key_verification/NoVerificationStrategy.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/git_client/ssh_host_key_verification/SshHostKeyVerificationStrategy.java
  src/main/java/org/jenkinsci/test/acceptance/po/GlobalSecurityConfig.java
  src/test/java/plugins/GitPluginTest.java
  src/test/java/plugins/WorkflowPluginTest.java
Labels: bug

#884 ByPass the FileDetector for things that are not files
  src/main/java/org/jenkinsci/test/acceptance/plugins/ssh_slaves/SshSlaveLauncher.java
  src/main/java/org/jenkinsci/test/acceptance/selenium/UselessFileDetectorReplacement.java
  src/test/java/plugins/SshSlavesPluginTest.java
Labels: bug

#885 Do not assume that `forkCount` is an integer
  src/main/java/org/jenkinsci/test/acceptance/utils/ElasticTime.java
Labels: bug

#879 installPlugin(File) now properly wait for plugin installation (#804)
  src/main/java/org/jenkinsci/test/acceptance/po/PluginManager.java
Labels: bug

#887 Enable JEP-229
  .github/dependabot.yml
  .github/release-drafter.yml
  .github/workflows/cd.yml
  .github/workflows/release-drafter.yml
  .mvn/extensions.xml
  .mvn/maven.config
  pom.xml
Labels: breaking, developer

#888 Fix javadoc errors
  docs/PAGE-OBJECTS.md
  src/main/java/org/jenkinsci/test/acceptance/FallbackConfig.java
  src/main/java/org/jenkinsci/test/acceptance/SshKeyPairGenerator.java
  src/main/java/org/jenkinsci/test/acceptance/controller/JenkinsController.java
  src/main/java/org/jenkinsci/test/acceptance/controller/TomcatController.java
  src/main/java/org/jenkinsci/test/acceptance/docker/fixtures/FtpdContainer.java
  src/main/java/org/jenkinsci/test/acceptance/guice/TestScope.java
  src/main/java/org/jenkinsci/test/acceptance/junit/AbstractJUnitTest.java
  src/main/java/org/jenkinsci/test/acceptance/junit/GlobalRule.java
  src/main/java/org/jenkinsci/test/acceptance/junit/RuleAnnotation.java
  src/main/java/org/jenkinsci/test/acceptance/junit/WithCredentials.java
  src/main/java/org/jenkinsci/test/acceptance/junit/WithPlugins.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/audit_trail/AuditTrailLogger.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/copyartifact/CopyArtifactBuildStep.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/credentials/Credential.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/credentials/CredentialsPage.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/credentials/ManagedCredentials.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/credentialsbinding/ManagedCredentialsBinding.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/dashboard_view/controls/ColumnsArea.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/dashboard_view/controls/JobFiltersArea.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/dashboard_view/controls/MainArea.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/dashboard_view/read/BreadCrumbs.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/logparser/LogParserPublisher.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/maven/MavenInstallation.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/stageview/StageViewBuild.java
  src/main/java/org/jenkinsci/test/acceptance/po/Axis.java
  src/main/java/org/jenkinsci/test/acceptance/po/BuildStep.java
  src/main/java/org/jenkinsci/test/acceptance/po/CapybaraPortingLayer.java
  src/main/java/org/jenkinsci/test/acceptance/po/CapybaraPortingLayerImpl.java
  src/main/java/org/jenkinsci/test/acceptance/po/ComputerLauncher.java
  src/main/java/org/jenkinsci/test/acceptance/po/ContainerPageObject.java
  src/main/java/org/jenkinsci/test/acceptance/po/Control.java
  src/main/java/org/jenkinsci/test/acceptance/po/Describable.java
  src/main/java/org/jenkinsci/test/acceptance/po/Job.java
  src/main/java/org/jenkinsci/test/acceptance/po/LdapSecurityRealm.java
  src/main/java/org/jenkinsci/test/acceptance/po/LdapSecurityRealm_Pre1_10.java
  src/main/java/org/jenkinsci/test/acceptance/po/ListViewColumn.java
  src/main/java/org/jenkinsci/test/acceptance/po/PageArea.java
  src/main/java/org/jenkinsci/test/acceptance/po/PageAreaImpl.java
  src/main/java/org/jenkinsci/test/acceptance/po/PageObject.java
  src/main/java/org/jenkinsci/test/acceptance/po/Parameter.java
  src/main/java/org/jenkinsci/test/acceptance/po/PluginManager.java
  src/main/java/org/jenkinsci/test/acceptance/po/PluginPageObject.java
  src/main/java/org/jenkinsci/test/acceptance/po/PostBuildStep.java
  src/main/java/org/jenkinsci/test/acceptance/po/Scm.java
  src/main/java/org/jenkinsci/test/acceptance/po/View.java
  src/main/java/org/jenkinsci/test/acceptance/selenium/Scroller.java
  src/main/java/org/jenkinsci/test/acceptance/server/JenkinsControllerPoolProcess.java
  src/main/java/org/jenkinsci/test/acceptance/slave/SlaveController.java
  src/main/java/org/jenkinsci/test/acceptance/utils/ElasticTime.java
  src/main/java/org/jenkinsci/test/acceptance/utils/SauceLabsConnection.java
  src/main/java/org/jenkinsci/test/acceptance/utils/groovy/ClosureScript.java
  src/main/java/org/jenkinsci/test/acceptance/utils/pluginreporter/TextFileExercisedPluginReporter.java
  src/test/java/plugins/CopyArtifactPluginTest.java
  src/test/java/plugins/NodeLabelParameterPluginTest.java
Labels: bug

#883 [SECURITY] Fix Temporary Directory Hijacking or Information Disclosure Vulnerability
  src/main/java/org/jenkinsci/test/acceptance/controller/LocalController.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/git/GitRepo.java
  src/test/java/plugins/GerritTriggerTest.java
Labels: chore

#889 More javadoc fixes
  src/main/java/org/jenkinsci/test/acceptance/FallbackConfig.java
  src/main/java/org/jenkinsci/test/acceptance/junit/AbstractJUnitTest.java
  src/main/java/org/jenkinsci/test/acceptance/junit/GlobalRule.java
  src/main/java/org/jenkinsci/test/acceptance/junit/RuleAnnotation.java
  src/main/java/org/jenkinsci/test/acceptance/junit/Wait.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/ssh_slaves/SshSlaveLauncher.java
  src/main/java/org/jenkinsci/test/acceptance/po/CapybaraPortingLayer.java
  src/main/java/org/jenkinsci/test/acceptance/po/CapybaraPortingLayerImpl.java
  src/main/java/org/jenkinsci/test/acceptance/po/Control.java
  src/main/java/org/jenkinsci/test/acceptance/po/PageArea.java
  src/main/java/org/jenkinsci/test/acceptance/po/Trigger.java
  src/main/java/org/jenkinsci/test/acceptance/recorder/HarRecorder.java
  src/main/java/org/jenkinsci/test/acceptance/slave/SlaveController.java
  src/main/java/org/jenkinsci/test/acceptance/utils/ElasticTime.java
  src/main/java/org/jenkinsci/test/acceptance/utils/IOUtil.java
Labels: bug

#890 Use proper `@see` javadoc notation
  src/main/java/org/jenkinsci/test/acceptance/junit/Wait.java
  src/main/java/org/jenkinsci/test/acceptance/slave/SlaveController.java
Labels: skip-changelog

#892 fix: Workaround (possible) javadoc 11 issue with `@see` and generics
  src/main/java/org/jenkinsci/test/acceptance/junit/Wait.java
Labels: skip-changelog

#893 Add CI stage
  Jenkinsfile
Labels: chore

#869 Adapt to removing items from sidebar
  src/main/java/org/jenkinsci/test/acceptance/po/Slave.java
  src/test/java/core/ArtifactsTest.java
  src/test/java/core/SlaveTest.java
  src/test/java/plugins/CopyArtifactPluginTest.java
  src/test/java/plugins/DeclarativePipelineTest.java
  src/test/java/plugins/NodeLabelParameterPluginTest.java
  src/test/java/plugins/OwnershipPluginTest.java
  src/test/java/plugins/PrioritySorterPluginTest.java
  src/test/java/plugins/WorkflowPluginTest.java
Labels: enhancement

#896 Remove redundant project.build.sourceEncoding property
  pom.xml
Labels: chore

#899 tests: Address #assertThat deprecations
  src/test/java/core/CreateItemTest.java
  src/test/java/core/InstallWizardTest.java
  src/test/java/core/JenkinsDatabaseSecurityRealmTest.java
  src/test/java/org/jenkinsci/test/acceptance/recorder/TestRecorderRuleTest.java
  src/test/java/plugins/AntisamyMarkupFormatterTest.java
  src/test/java/plugins/AuthorizeProjectTest.java
  src/test/java/plugins/ConfigFileProviderTest.java
  src/test/java/plugins/CredentialsBindingTest.java
  src/test/java/plugins/MSBuildPluginTest.java
Labels: tests

#900 Address IOUtils' charset deprecations
  src/main/java/org/jenkinsci/test/acceptance/SshKeyPair.java
  src/main/java/org/jenkinsci/test/acceptance/controller/JenkinsLogWatcher.java
  src/main/java/org/jenkinsci/test/acceptance/docker/fixtures/JiraContainer.java
  src/main/java/org/jenkinsci/test/acceptance/junit/Resource.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/audit_trail/AuditTrailLogger.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/git/GitRepo.java
  src/main/java/org/jenkinsci/test/acceptance/po/Jenkins.java
  src/main/java/org/jenkinsci/test/acceptance/po/Job.java
  src/main/java/org/jenkinsci/test/acceptance/po/ToolInstallation.java
  src/main/java/org/jenkinsci/test/acceptance/po/WizardLogin.java
  src/main/java/org/jenkinsci/test/acceptance/po/WorkflowMultiBranchJob.java
  src/test/java/core/FreestyleJobTest.java
  src/test/java/plugins/ArtifactoryPluginTest.java
  src/test/java/plugins/DeployPluginTest.java
  src/test/java/plugins/GerritTriggerTest.java
  src/test/java/plugins/JabberPluginTest.java
  src/test/java/plugins/WorkflowMultibranchTest.java
  src/test/java/plugins/WorkflowPluginTest.java
Labels: tests

#901 docs: Address javadoc link warnings
  src/main/java/org/jenkinsci/test/acceptance/ByFactory.java
  src/main/java/org/jenkinsci/test/acceptance/Config.java
  src/main/java/org/jenkinsci/test/acceptance/po/Control.java
  src/main/java/org/jenkinsci/test/acceptance/po/PageArea.java
  src/main/java/org/jenkinsci/test/acceptance/po/PageAreaImpl.java
  src/main/java/org/jenkinsci/test/acceptance/recorder/HarRecorder.java
  src/test/java/plugins/JabberPluginTest.java
Labels: documentation

#903 Address JUnit assumption deprecation
  src/main/java/org/jenkinsci/test/acceptance/junit/JenkinsAcceptanceTestRule.java
  src/main/java/org/jenkinsci/test/acceptance/junit/Native.java
  src/main/java/org/jenkinsci/test/acceptance/junit/TestActivation.java
  src/main/java/org/jenkinsci/test/acceptance/junit/WithCredentials.java
  src/main/java/org/jenkinsci/test/acceptance/junit/WithDocker.java
  src/main/java/org/jenkinsci/test/acceptance/junit/WithInstallWizard.java
  src/main/java/org/jenkinsci/test/acceptance/junit/WithJavaOptions.java
  src/main/java/org/jenkinsci/test/acceptance/junit/WithOS.java
  src/main/java/org/jenkinsci/test/acceptance/junit/WithPlugins.java
  src/main/java/org/jenkinsci/test/acceptance/po/Job.java
  src/main/java/org/jenkinsci/test/acceptance/update_center/UpdateCenterMetadata.java
Labels: chore

#902 docs: Fix javadoc code warnings
  src/main/java/org/jenkinsci/test/acceptance/FallbackConfig.java
  src/main/java/org/jenkinsci/test/acceptance/SshKeyPairGenerator.java
  src/main/java/org/jenkinsci/test/acceptance/controller/LocalController.java
  src/main/java/org/jenkinsci/test/acceptance/docker/fixtures/GitContainer.java
  src/main/java/org/jenkinsci/test/acceptance/junit/WithPlugins.java
  src/main/java/org/jenkinsci/test/acceptance/po/PluginPageObject.java
  src/main/java/org/jenkinsci/test/acceptance/selenium/Scroller.java
  src/main/java/org/jenkinsci/test/acceptance/selenium/UselessFileDetectorReplacement.java
  src/main/java/org/jenkinsci/test/acceptance/utils/ElasticTime.java
  src/main/java/org/jenkinsci/test/acceptance/utils/SauceLabsConnection.java
Labels: documentation

#904 chore: Misc Java 8 cleanup
  src/main/java/org/jenkinsci/test/acceptance/FallbackConfig.java
  src/main/java/org/jenkinsci/test/acceptance/Matchers.java
  src/main/java/org/jenkinsci/test/acceptance/controller/WinstoneController.java
  src/main/java/org/jenkinsci/test/acceptance/guice/TestLifecycle.java
  src/main/java/org/jenkinsci/test/acceptance/junit/FailureDiagnostics.java
  src/main/java/org/jenkinsci/test/acceptance/junit/JenkinsAcceptanceTestRule.java
  src/main/java/org/jenkinsci/test/acceptance/junit/Since.java
  src/main/java/org/jenkinsci/test/acceptance/junit/Wait.java
  src/main/java/org/jenkinsci/test/acceptance/junit/WithDocker.java
  src/main/java/org/jenkinsci/test/acceptance/junit/WithJavaOptions.java
  src/main/java/org/jenkinsci/test/acceptance/junit/WithOS.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/audit_trail/AuditTrailLogger.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/config_file_provider/MavenSettingsConfig.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/credentials/StringCredentials.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/credentialsbinding/ManagedCredentialsBinding.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/dashboard_view/BuildStatisticsPortlet.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/dashboard_view/LatestBuildsPortlet.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/dashboard_view/controls/ColumnsArea.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/email_ext/GlobalConfig.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/git/GitRepo.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/git_client/JGitInstallation.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/html_publisher/HtmlPublisher.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/parameterized_trigger/ParameterizedTrigger.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/parameterized_trigger/TriggerCallBuildStep.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/parameterized_trigger/TriggerConfig.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/post_build_script/PostBuildScript.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/priority_sorter/PriorityConfig.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/workflow_shared_library/WorkflowSharedLibraryGlobalConfig.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/xunit/XUnitPublisher.java
  src/main/java/org/jenkinsci/test/acceptance/po/ArtifactManagement.java
  src/main/java/org/jenkinsci/test/acceptance/po/Build.java
  src/main/java/org/jenkinsci/test/acceptance/po/Control.java
  src/main/java/org/jenkinsci/test/acceptance/po/Folder.java
  src/main/java/org/jenkinsci/test/acceptance/po/GlobalSecurityConfig.java
  src/main/java/org/jenkinsci/test/acceptance/po/GlobalToolConfig.java
  src/main/java/org/jenkinsci/test/acceptance/po/Job.java
  src/main/java/org/jenkinsci/test/acceptance/po/ListView.java
  src/main/java/org/jenkinsci/test/acceptance/po/MatrixProject.java
  src/main/java/org/jenkinsci/test/acceptance/po/ToolInstallation.java
  src/main/java/org/jenkinsci/test/acceptance/po/User.java
  src/main/java/org/jenkinsci/test/acceptance/po/WorkflowMultiBranchJob.java
  src/main/java/org/jenkinsci/test/acceptance/update_center/LocalOverrideUpdateCenterMetadataDecoratorImpl.java
  src/main/java/org/jenkinsci/test/acceptance/utils/SHA1Sum.java
  src/main/java/org/jenkinsci/test/acceptance/utils/SauceLabsConnection.java
  src/main/java/org/jenkinsci/test/acceptance/utils/SupportBundleRequest.java
  src/main/java/org/jenkinsci/test/acceptance/utils/pluginreporter/ExercisedPluginsReporter.java
  src/test/java/core/JenkinsDatabaseSecurityRealmTest.java
  src/test/java/plugins/AntPluginTest.java
  src/test/java/plugins/DeclarativePipelineTest.java
  src/test/java/plugins/GerritTriggerTest.java
  src/test/java/plugins/JavadocPluginTest.java
Labels: chore

#909 getAvailableVersionForPlugin now properly waits for plugin list to refresh, and becomes public
  src/main/java/org/jenkinsci/test/acceptance/po/PluginManager.java
Labels: enhancement
