Repository jenkinsci/acceptance-test-harness, pull requests merged in 2022-04, with the labels that each got.

#753 Fix credentials and weekly changes
  src/main/java/org/jenkinsci/test/acceptance/plugins/credentials/CredentialsPage.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/credentials/DomainPage.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/ssh_slaves/SshSlaveLauncher.java
  src/test/java/plugins/DashboardViewPluginTest.java
Labels: enhancement

#755 Format Jenkinsfile
  Jenkinsfile
Labels: chore

#657 Adapt `GlobalSecurityConfig` PO to modified layout of `GlobalSecurityConfiguration`
  src/main/java/org/jenkinsci/test/acceptance/po/CapybaraPortingLayerImpl.java
  src/main/java/org/jenkinsci/test/acceptance/po/GlobalSecurityConfig.java
Labels: internal

#761 Exchange Jenkins http mirror in favor of https
  grab-latest-rc.sh
  src/main/resources/ath-container/run.sh
Labels: chore
