Repository jenkinsci/acceptance-test-harness, pull requests merged in 2022-10, with the labels that each got.

#958 Misc Java 11 cleanup
  src/main/java/org/jenkinsci/test/acceptance/controller/JBossController.java
  src/main/java/org/jenkinsci/test/acceptance/controller/TomcatController.java
  src/main/java/org/jenkinsci/test/acceptance/docker/fixtures/FtpdContainer.java
  src/main/java/org/jenkinsci/test/acceptance/docker/fixtures/IPasswordDockerContainer.java
  src/main/java/org/jenkinsci/test/acceptance/docker/fixtures/JabberContainer.java
  src/main/java/org/jenkinsci/test/acceptance/junit/FailureDiagnostics.java
  src/main/java/org/jenkinsci/test/acceptance/junit/JenkinsAcceptanceTestRule.java
  src/main/java/org/jenkinsci/test/acceptance/junit/Native.java
  src/main/java/org/jenkinsci/test/acceptance/junit/Wait.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/dashboard_view/LatestBuildsPortlet.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/git/GitRepo.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/jabber/JabberGlobalConfig.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/job_dsl/JobDslLookupStrategy.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/job_dsl/JobDslRemovedConfigFilesAction.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/job_dsl/JobDslRemovedViewAction.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/workflow_multibranch/GithubBranchSource.java
  src/main/java/org/jenkinsci/test/acceptance/po/Build.java
  src/main/java/org/jenkinsci/test/acceptance/po/Control.java
  src/main/java/org/jenkinsci/test/acceptance/po/FormValidation.java
  src/main/java/org/jenkinsci/test/acceptance/po/JenkinsLogger.java
  src/main/java/org/jenkinsci/test/acceptance/po/JobsMixIn.java
  src/main/java/org/jenkinsci/test/acceptance/po/WizardLogin.java
  src/main/java/org/jenkinsci/test/acceptance/recorder/JUnitScreenRecorder.java
  src/main/java/org/jenkinsci/test/acceptance/utils/IOUtil.java
  src/main/java/org/jenkinsci/test/acceptance/utils/aether/ConsoleTransferListener.java
Labels: chore

#960 Forward compatibility for submit buttons using `.jenkins-button` classes
  src/main/java/org/jenkinsci/test/acceptance/plugins/matrix_auth/MatrixAuthorizationStrategy.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/matrix_auth/ProjectMatrixProperty.java
  src/main/java/org/jenkinsci/test/acceptance/po/ConfigurablePageObject.java
Labels: bug, enhancement

#961 Run ATH on a weekly basis
  Jenkinsfile
Labels: chore

#962 Use a numeric cron value
  Jenkinsfile
Labels: chore

#971 remove versions specified by the parent
  pom.xml
Labels: skip-changelog, chore

#972 prevent split modules
  pom.xml
  src/main/java/org/jenkinsci/test/acceptance/SshKeyPairGenerator.java
Labels: chore

#977 Remove references to `--ajp13Port`
  src/main/java/org/jenkinsci/test/acceptance/controller/WinstoneController.java
  src/main/java/org/jenkinsci/test/acceptance/controller/WinstoneDockerController.java
Labels: enhancement

#978 make the test work so it can be debugged on windows
  src/test/java/plugins/ConfigFileProviderTest.java
Labels: chore

#979 Ensure that we disable sticky elements when changing navigation
  src/main/java/org/jenkinsci/test/acceptance/plugins/config_file_provider/ConfigFileProvider.java
Labels: fix
