Repository jenkinsci/acceptance-test-harness, pull requests merged in 2022-07, with the labels that each got.

#814 Upgrade `docker-fixtures` from 1.11 to 1.12
  pom.xml
  src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/DockerAgentContainer/Dockerfile
  src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/SshAgentContainer/Dockerfile
  src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/XvncSlaveContainer/Dockerfile
  src/test/java/core/FormValidationTest.java
  src/test/java/plugins/SshSlavesPluginTest.java
Labels: dependencies

#824 Raise PR limit in dependabot while we clear the backlog
  .github/dependabot.yml
Labels: chore

#823 Exchange xmlunit with maintained xmlunit-legacy
  pom.xml
Labels: dependencies

#845 build: Update mail to 2.x
  pom.xml
  src/main/java/org/jenkinsci/test/acceptance/docker/fixtures/MailhogContainer.java
  src/test/java/plugins/WorkflowMultibranchTest.java
Labels: dependencies

#856 build: Remove old httpclient version
  pom.xml
Labels: dependencies

#859 EOL JSR 305
  pom.xml
  src/main/java/org/jenkinsci/test/acceptance/FallbackConfig.java
  src/main/java/org/jenkinsci/test/acceptance/Matchers.java
  src/main/java/org/jenkinsci/test/acceptance/controller/ExistingJenkinsController.java
  src/main/java/org/jenkinsci/test/acceptance/controller/JenkinsController.java
  src/main/java/org/jenkinsci/test/acceptance/controller/LocalController.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/dashboard_view/DashboardView.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/dashboard_view/JobsGridPortlet.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/ssh_slaves/SshSlaveLauncher.java
  src/main/java/org/jenkinsci/test/acceptance/po/Artifact.java
  src/main/java/org/jenkinsci/test/acceptance/po/CapybaraPortingLayer.java
  src/main/java/org/jenkinsci/test/acceptance/po/CapybaraPortingLayerImpl.java
  src/main/java/org/jenkinsci/test/acceptance/po/Control.java
  src/main/java/org/jenkinsci/test/acceptance/po/FormValidation.java
  src/main/java/org/jenkinsci/test/acceptance/po/PageArea.java
  src/main/java/org/jenkinsci/test/acceptance/po/PageAreaImpl.java
  src/main/java/org/jenkinsci/test/acceptance/po/PageObject.java
  src/main/java/org/jenkinsci/test/acceptance/po/TopLevelItem.java
  src/main/java/org/jenkinsci/test/acceptance/po/WorkflowJob.java
  src/main/java/org/jenkinsci/test/acceptance/update_center/PluginMetadata.java
  src/main/java/org/jenkinsci/test/acceptance/update_center/PluginSpec.java
  src/main/java/org/jenkinsci/test/acceptance/utils/AccessTokenGenerator.java
  src/main/java/org/jenkinsci/test/acceptance/utils/HttpUtils.java
  src/main/java/org/jenkinsci/test/acceptance/utils/IOUtil.java
  src/main/java/org/jenkinsci/test/acceptance/utils/pluginreporter/ConsoleExercisedPluginReporter.java
Labels: chore

#858 chore: Minor pom cleanup
  pom.xml
Labels: chore

#861 Remove prelaunching functionality
  README.md
  docs/PRELAUNCH.md
  pom.xml
  src/main/java/org/jenkinsci/test/acceptance/FallbackConfig.java
  src/main/java/org/jenkinsci/test/acceptance/junit/GlobalRule.java
  src/main/java/org/jenkinsci/test/acceptance/junit/RuleAnnotation.java
  src/main/java/org/jenkinsci/test/acceptance/log/LogListener.java
  src/main/java/org/jenkinsci/test/acceptance/server/JenkinsControllerPoolProcess.java
  src/main/java/org/jenkinsci/test/acceptance/server/PooledJenkinsController.java
  src/test/java/UnixDomainSocketTestServer.java
Labels: breaking

#864 Upgrade release-plugin to 3.0.0-M6
  pom.xml
Labels: fix

#867 Deflake SshSlavesPluginTest
  src/main/java/org/jenkinsci/test/acceptance/plugins/credentials/Credential.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/ssh_slaves/SshSlaveLauncher.java
Labels: tests

#873 Revert "Remove prelaunching functionality (#861)"
  README.md
  docs/PRELAUNCH.md
  pom.xml
  src/main/java/org/jenkinsci/test/acceptance/FallbackConfig.java
  src/main/java/org/jenkinsci/test/acceptance/junit/GlobalRule.java
  src/main/java/org/jenkinsci/test/acceptance/junit/RuleAnnotation.java
  src/main/java/org/jenkinsci/test/acceptance/log/LogListener.java
  src/main/java/org/jenkinsci/test/acceptance/server/JenkinsControllerPoolProcess.java
  src/main/java/org/jenkinsci/test/acceptance/server/PooledJenkinsController.java
  src/test/java/UnixDomainSocketTestServer.java
Labels: bug
