Repository jenkinsci/acceptance-test-harness, pull requests merged in 2023-06, with the labels that each got.

#1208 Group selenium deps
  .github/renovate.json
Labels: chore

#1219 Update test cases to gradle 8
  src/test/resources/artifactory_plugin/quickstart/build.gradle
  src/test/resources/artifactory_plugin/quickstart/gradle/wrapper/gradle-wrapper.jar
  src/test/resources/artifactory_plugin/quickstart/gradle/wrapper/gradle-wrapper.properties
  src/test/resources/artifactory_plugin/quickstart/gradlew
  src/test/resources/artifactory_plugin/quickstart/gradlew.bat
Labels: dependencies

#1223 disable surefire reuse of forks
  pom.xml
Labels: developer

#1224 revert to junit4
  pom.xml
Labels: developer

#1228 improve the contract around HARRecording
  src/main/java/org/jenkinsci/test/acceptance/FallbackConfig.java
  src/main/java/org/jenkinsci/test/acceptance/recorder/HarRecorder.java
Labels: developer

#1234 Forward compatibility with Java 17 in JacocoPluginTest
  src/test/java/plugins/JacocoPluginTest.java
  src/test/resources/jacoco/test/pom.xml
Labels: enhancement

#1238 Workaround ant's specific Java version test
  src/test/java/plugins/AntPluginTest.java
Labels: chore

#1240 Temporarily ignore scriptler tests
  src/test/java/plugins/ScriptlerPluginTest.java
Labels: chore

#1241 Add Java 17 to jdk matrix
  Jenkinsfile
  src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/JavaGitContainer/Dockerfile
Labels: enhancement

#1243 Run CI builds on Java 17 only
  Jenkinsfile
Labels: chore

#1250 Replace 'additionalparam' with doclint
  pom.xml
Labels: chore

#1253 Adapt to scriptler plugin changes
  src/main/java/org/jenkinsci/test/acceptance/plugins/scriptler/Script.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/scriptler/Scriptler.java
  src/test/java/plugins/ScriptlerPluginTest.java
Labels: tests

#1263 Update maven URL to be more robust for maven updates
  src/main/resources/ath-container/Dockerfile
Labels: chore

#1265 Update LTS in Maven profile to 2.401.2
  pom.xml
Labels: developer
