Repository jenkinsci/acceptance-test-harness, pull requests merged in 2023-08, with the labels that each got.

#1264 forward compatibility with core-8180
  src/main/java/org/jenkinsci/test/acceptance/plugins/job_dsl/JobDslBuildStep.java
  src/test/java/plugins/AntPluginTest.java
Labels: enhancement

#1244 Forward compatibility with adding last build status to job page
  src/main/java/org/jenkinsci/test/acceptance/po/TopLevelItem.java
Labels: enhancement

#1314 use custom DNS in the ath container to enable HAR recording
  src/main/resources/ath-container/run.sh
Labels: bug, developer

#1316 forward compatibility for core-8340
  src/main/java/org/jenkinsci/test/acceptance/po/CapybaraPortingLayerImpl.java
  src/main/java/org/jenkinsci/test/acceptance/po/Control.java
Labels: enhancement

#1323 Revert "use custom DNS in the ath container to enable HAR recording"
  src/main/resources/ath-container/run.sh
Labels: bug

#1321 Install OpenJDK 21 in ATH image
  src/main/resources/ath-container/Dockerfile
  src/main/resources/ath-container/set-java.sh
Labels: developer

#1327 Update maven in tests
  src/test/java/plugins/DeclarativePipelineTest.java
  src/test/java/plugins/ExternalWorkspaceManagerPluginTest.java
  src/test/java/plugins/MavenPluginTest.java
  src/test/java/plugins/PipelineTest.java
  src/test/java/plugins/WorkflowMultibranchTest.java
  src/test/java/plugins/WorkflowPluginTest.java
Labels: dependencies

#1329 Use jenkinsci test project for WorkflowPluginTest
  src/test/java/plugins/WorkflowPluginTest.java
Labels: tests

#1328 forward compatibility for core-8340
  src/main/java/org/jenkinsci/test/acceptance/plugins/build_timeout/BuildTimeout.java
  src/main/java/org/jenkinsci/test/acceptance/po/Control.java
Labels: enhancement

#1334 Support Java 21 on AArch64
  src/main/resources/ath-container/Dockerfile
Labels: regression

#1324 Test on Java 21
  Jenkinsfile
Labels: tests

#1343 Update LTS profile
  pom.xml
Labels: dependencies

#1344 Fixes #1341 - Skip ownership tests
  src/main/java/org/jenkinsci/test/acceptance/plugins/ownership/OwnershipAction.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/ownership/OwnershipGlobalConfig.java
  src/test/java/plugins/OwnershipPluginTest.java
Labels: chore
