Repository jenkinsci/acceptance-test-harness, pull requests merged in 2023-07, with the labels that each got.

#1273 chore(Jenkinsfile) discard old builds (5/PR and 10 on primary branch)
  Jenkinsfile
Labels: chore

#1230 Plugin manager app bar forward compatibility
  pom.xml
  src/main/java/org/jenkinsci/test/acceptance/po/PluginManager.java
Labels: enhancement

#1278 Fix deploy plugin test
  src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/Tomcat10Container/Dockerfile
Labels: bug

#1279 Use artifact caching proxy for `acceptance-test-harness`
  Jenkinsfile
Labels: chore

#1285 replace dumpling with a call to jstack
  pom.xml
  src/main/java/org/jenkinsci/test/acceptance/controller/LocalController.java
Labels: bug

#1261 forward compatibility for core-7938
  pom.xml
  src/main/java/org/jenkinsci/test/acceptance/po/Build.java
  src/main/java/org/jenkinsci/test/acceptance/po/CapybaraPortingLayerImpl.java
  src/main/java/org/jenkinsci/test/acceptance/po/ConfigurablePageObject.java
  src/main/java/org/jenkinsci/test/acceptance/po/Control.java
  src/main/java/org/jenkinsci/test/acceptance/po/Job.java
  src/main/java/org/jenkinsci/test/acceptance/po/PluginManager.java
  src/main/java/org/jenkinsci/test/acceptance/po/User.java
  src/main/java/org/jenkinsci/test/acceptance/po/View.java
  src/main/java/org/jenkinsci/test/acceptance/po/WorkflowJob.java
  src/main/java/org/jenkinsci/test/acceptance/po/Workspace.java
  src/test/java/core/PluginManagerTest.java
  src/test/java/plugins/ConfigFileProviderTest.java
Labels: enhancement

#1301 Don't look for project prefix to page title
  src/test/java/plugins/DashboardViewPluginTest.java
Labels: tests
