Repository jenkinsci/acceptance-test-harness, pull requests merged in 2023-04, with the labels that each got.

#1087 Sort dependencies
  pom.xml
Labels: chore

#1086 Clean up shell scripts
  ath-container.sh
  grab-latest-rc.sh
  jut-server.sh
  src/main/resources/ath-container/run.sh
  src/main/resources/ath-container/set-java.sh
  src/main/resources/ath-container/vnc.sh
Labels: internal

#1089 Use `<<-` here document redirection operator where applicable
  src/main/resources/ath-container/run.sh
Labels: internal

#1088 Restore scriptler tests
  src/main/java/org/jenkinsci/test/acceptance/plugins/scriptler/Script.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/scriptler/Scriptler.java
  src/test/java/plugins/ScriptlerPluginTest.java
Labels: enhancement

#1085 Add tests for DisplayUrlApi
  pom.xml
  src/test/java/plugins/DisplayUrlApiTest.java
Labels: enhancement

#1096 Upgrade parent POM from 1.94 to 1.97
  pom.xml
Labels: dependencies

#1091 Add test for declarative migration assistant and pipeline with unstable tests
  src/test/java/plugins/DeclarativeAssistantMigrationTest.java
  src/test/java/plugins/PipelineTest.java
Labels: enhancement

#1100 Update Selenium parameter for Selenium 4
  src/main/java/org/jenkinsci/test/acceptance/FallbackConfig.java
Labels: bug

#1104 add tests for secure-requester-whitelist
  src/test/java/plugins/SecureRequesterWhitelistTest.java
Labels: enhancement

#1092 [#1053] Adding tests for cloudbees folders plugin
  src/test/java/plugins/FolderPluginTest.java
Labels: enhancement

#1102 [#1053] Adding tests for MSTestRunner plugin
  src/test/java/plugins/MSTestRunnerPluginTest.java
Labels: enhancement

#1106 [#1053] Add metrics test
  src/test/java/plugins/MetricsTest.java
Labels: enhancement

#1113 Collect Launchable test results for ATH workspace in ATH builds
  Jenkinsfile
Labels: internal

#1114 Upgrade parent POM from 1.97 to 1.98
  pom.xml
Labels: developer

#1116 Fix indentation in `Jenkinsfile`
  Jenkinsfile
Labels: skip-changelog

#1117 Refactor combinations in `Jenkinsfile` for readability
  Jenkinsfile
Labels: skip-changelog, chore

#860 make Build.isInProgress also cover post building stages. (deflake core.FreestyleJobTest#discardBuilds)
  src/main/java/org/jenkinsci/test/acceptance/Matchers.java
  src/main/java/org/jenkinsci/test/acceptance/po/Build.java
Labels: bug, developer

#1071 Add more test for configfile provider plugin
  src/main/java/org/jenkinsci/test/acceptance/utils/PipelineTestUtils.java
  src/test/java/plugins/ConfigFileProviderTest.java
Labels: enhancement

#1119 Address `#withTimeout()` deprecations
  src/main/java/org/jenkinsci/test/acceptance/FallbackConfig.java
  src/main/java/org/jenkinsci/test/acceptance/docker/fixtures/JiraContainer.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/configuration_as_code/JcascManage.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/ssh_credentials/SshCredentialDialog.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/ssh_slaves/SshSlaveLauncher.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/workflow_multibranch/GithubBranchSource.java
  src/main/java/org/jenkinsci/test/acceptance/po/Build.java
  src/main/java/org/jenkinsci/test/acceptance/po/CapybaraPortingLayerImpl.java
  src/main/java/org/jenkinsci/test/acceptance/po/Control.java
  src/main/java/org/jenkinsci/test/acceptance/po/Jenkins.java
  src/main/java/org/jenkinsci/test/acceptance/po/JenkinsLogger.java
  src/main/java/org/jenkinsci/test/acceptance/po/JobsMixIn.java
  src/main/java/org/jenkinsci/test/acceptance/po/Login.java
  src/main/java/org/jenkinsci/test/acceptance/po/PageObject.java
  src/main/java/org/jenkinsci/test/acceptance/po/PluginManager.java
  src/main/java/org/jenkinsci/test/acceptance/po/ToolInstallation.java
  src/main/java/org/jenkinsci/test/acceptance/po/UpdateCenter.java
  src/main/java/org/jenkinsci/test/acceptance/po/ViewsMixIn.java
  src/main/java/org/jenkinsci/test/acceptance/po/WizardCustomizeJenkins.java
  src/main/java/org/jenkinsci/test/acceptance/po/WorkflowJob.java
  src/main/java/org/jenkinsci/test/acceptance/po/WorkflowMultiBranchJob.java
  src/main/java/org/jenkinsci/test/acceptance/selenium/Scroller.java
  src/test/java/core/FreestyleJobTest.java
  src/test/java/plugins/MetricsTest.java
  src/test/java/plugins/SshSlavesPluginTest.java
Labels: chore

#1122 Upgrade Extensibility API from 1.5 to 1.6
  pom.xml
Labels: dependencies, java

#1080 Forward compatibility for refresh update sites button change
  src/main/java/org/jenkinsci/test/acceptance/po/PluginManager.java
Labels: enhancement

#1125 Address `#pollingEvery(long duration, TimeUnit unit)` deprecation
  src/main/java/org/jenkinsci/test/acceptance/junit/Wait.java
  src/main/java/org/jenkinsci/test/acceptance/po/CapybaraPortingLayerImpl.java
  src/main/java/org/jenkinsci/test/acceptance/po/Control.java
Labels: removed

#1126 Disable concurrent builds on the main branch
  Jenkinsfile
Labels: chore

#1132 Add Java 17 to Docker image
  src/main/resources/ath-container/Dockerfile
  src/main/resources/ath-container/set-java.sh
Labels: developer

#1130 Address `#pageLoadTimeout()` and `#implicitlyWait()` deprecation
  src/main/java/org/jenkinsci/test/acceptance/FallbackConfig.java
Labels: chore

#1124 Remove deprecated `withTimeout(long duration, TimeUnit unit)` in favor of `withTimeout(Duration timeout)`
  src/main/java/org/jenkinsci/test/acceptance/junit/Wait.java
  src/main/java/org/jenkinsci/test/acceptance/po/CapybaraPortingLayerImpl.java
Labels: removed

#1139 Remove CentOS 6 tests
  docs/CONTROLLER.md
  vagrant/centos/Vagrantfile
  vagrant/opensuse/Vagrantfile
  vagrant/readme.txt
  vagrant/ubuntu/Vagrantfile
  veewee/definitions/jenkins-test-centos-6.0/base.sh
  veewee/definitions/jenkins-test-centos-6.0/chef.sh
  veewee/definitions/jenkins-test-centos-6.0/cleanup.sh
  veewee/definitions/jenkins-test-centos-6.0/definition.rb
  veewee/definitions/jenkins-test-centos-6.0/ks.cfg
  veewee/definitions/jenkins-test-centos-6.0/puppet.sh
  veewee/definitions/jenkins-test-centos-6.0/ruby.sh
  veewee/definitions/jenkins-test-centos-6.0/vagrant.sh
  veewee/definitions/jenkins-test-centos-6.0/virtualbox.sh
  veewee/definitions/jenkins-test-centos-6.0/zerodisk.sh
  veewee/definitions/jenkins-test-opensuse-11.4/autoinst_en.xml
  veewee/definitions/jenkins-test-opensuse-11.4/definition.rb
  veewee/definitions/jenkins-test-opensuse-11.4/postinstall.sh
  veewee/readme.txt
Labels: removed

#1140 Remove unused imports
  src/main/java/org/jenkinsci/test/acceptance/FallbackConfig.java
  src/main/java/org/jenkinsci/test/acceptance/junit/JenkinsAcceptanceTestRule.java
  src/main/java/org/jenkinsci/test/acceptance/junit/Wait.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/git/GitRepo.java
  src/main/java/org/jenkinsci/test/acceptance/po/Control.java
  src/main/java/org/jenkinsci/test/acceptance/po/Slave.java
  src/main/java/org/jenkinsci/test/acceptance/utils/SauceLabsConnection.java
  src/test/java/plugins/OwnershipPluginTest.java
Labels: chore

#1142 Track geckodriver
  .github/dependabot.yml
  .github/renovate.json
  src/main/resources/ath-container/Dockerfile
Labels: chore

#1141 Update geckodriver from 0.32.3 to 0.33.0
  src/main/resources/ath-container/Dockerfile
Labels: dependencies

#1145 Fix geckodriver detection
  .github/renovate.json
Labels: chore

#1147 Remove jcl-api because it doesn't exist
  pom.xml
Labels: dependencies
