Repository jenkinsci/acceptance-test-harness, pull requests merged in 2023-05, with the labels that each got.

#1152 Update LTS Maven profile in ATH to 2.387.3
  pom.xml
Labels: dependencies

#1138 Add Jenkins core commit to Launchable build for LTS line
  Jenkinsfile
Labels: skip-changelog

#1153 Upgrade Maven from 3.3.9 to 3.8.1
  pom.xml
  src/main/java/org/jenkinsci/test/acceptance/utils/aether/AetherModule.java
Labels: dependencies, java

#1156 Ignore Maven dependency updates
  .github/renovate.json
Labels: skip-changelog

#1067 [#1053] Adding more credentials tests
  src/main/java/org/jenkinsci/test/acceptance/plugins/credentials/AbstractCredentialsTest.java
  src/main/java/org/jenkinsci/test/acceptance/po/WizardCreateAdminUser.java
  src/main/resources/ath-container/Dockerfile
  src/test/java/plugins/CredentialsBindingTest.java
  src/test/java/plugins/PlainCredentialsBindingTest.java
  src/test/java/plugins/SSHCredentialsTest.java
  src/test/resources/credentialsbinding/secretFile
  src/test/resources/credentialsbinding/secretFileScript
  src/test/resources/credentialsbinding/secretFileScriptWindows
  src/test/resources/credentialsbinding/secretTextScript
  src/test/resources/credentialsbinding/secretTextScriptWindows
  src/test/resources/credentialsbinding/secretZip.zip
  src/test/resources/credentialsbinding/secretZipFileScript
  src/test/resources/credentialsbinding/secretZipFileScriptWindows
  src/test/resources/credentialsbinding/sshUserPrivateKeyScript
  src/test/resources/credentialsbinding/sshUserPrivateKeyScriptWindows
  src/test/resources/credentialsbinding/usernameSplitPasswordScript
  src/test/resources/credentialsbinding/usernameSplitPasswordScriptWindows
  src/test/resources/credentialsbinding/usernameTogetherPasswordScript
  src/test/resources/credentialsbinding/usernameTogetherPasswordScriptWindows
  src/test/resources/plaincredentialsbinding/secretFile
Labels: enhancement

#1154 Forward compatibility for core-7911
  src/main/java/org/jenkinsci/test/acceptance/po/User.java
  src/main/java/org/jenkinsci/test/acceptance/po/View.java
Labels: enhancement

#1168 chore(Jenkinsfile) Use `jenkins/ath` instead of rebuilding it
  Jenkinsfile
Labels: chore

#1172 Show the image of the remote container in logging statement
  src/main/java/org/jenkinsci/test/acceptance/FallbackConfig.java
Labels: developer

#1177 Move to Guice 6
  .github/renovate.json
  pom.xml
Labels: dependencies, java

#1179 Remove use of Launchable shared library functionality
  Jenkinsfile
Labels: skip-changelog

#1182 Update hamcrest to non-deprecated package
  pom.xml
Labels: dependencies, java

#1190 Update hamcrest methods
  src/main/java/org/jenkinsci/test/acceptance/Matchers.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/credentials/CredentialsPage.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/credentials/DomainPage.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/gerrit_trigger/GerritTriggerServer.java
  src/main/java/org/jenkinsci/test/acceptance/po/Artifact.java
  src/main/java/org/jenkinsci/test/acceptance/po/Build.java
  src/main/java/org/jenkinsci/test/acceptance/po/ConfigurablePageObject.java
  src/main/java/org/jenkinsci/test/acceptance/po/Job.java
  src/main/java/org/jenkinsci/test/acceptance/po/Login.java
  src/main/java/org/jenkinsci/test/acceptance/po/View.java
  src/main/java/org/jenkinsci/test/acceptance/po/WizardCustomizeJenkins.java
  src/test/java/core/ArtifactsTest.java
  src/test/java/core/FreestyleJobTest.java
  src/test/java/core/ScriptTest.java
  src/test/java/core/SlaveTest.java
  src/test/java/org/jenkinsci/test/acceptance/recorder/HarRecorderTest.java
  src/test/java/org/jenkinsci/test/acceptance/recorder/TestRecorderRuleTest.java
  src/test/java/plugins/AntPluginTest.java
  src/test/java/plugins/AuditTrailPluginTest.java
  src/test/java/plugins/CoberturaPluginTest.java
  src/test/java/plugins/CopyArtifactPluginTest.java
  src/test/java/plugins/CredentialsBindingTest.java
  src/test/java/plugins/DeclarativePipelineTest.java
  src/test/java/plugins/DeployPluginTest.java
  src/test/java/plugins/ExternalWorkspaceManagerPluginTest.java
  src/test/java/plugins/GerritTriggerTest.java
  src/test/java/plugins/GitPluginTest.java
  src/test/java/plugins/JUnitPluginTest.java
  src/test/java/plugins/JabberPluginTest.java
  src/test/java/plugins/JobDslPluginTest.java
  src/test/java/plugins/LdapPluginTest.java
  src/test/java/plugins/MatrixPluginTest.java
  src/test/java/plugins/MatrixReloadedPluginTest.java
  src/test/java/plugins/MavenPluginTest.java
  src/test/java/plugins/NestedViewPluginTest.java
  src/test/java/plugins/OwnershipPluginTest.java
  src/test/java/plugins/PlainCredentialsBindingTest.java
  src/test/java/plugins/PostBuildScriptPluginTest.java
  src/test/java/plugins/ProjectDescriptionSetterPluginTest.java
  src/test/java/plugins/ScriptlerPluginTest.java
  src/test/java/plugins/WorkflowMultibranchTest.java
  src/test/java/plugins/WsCleanupPluginTest.java
Labels: tests

#1194 Revert changes to `ExternalWorkspaceManagerPluginTest` from #1180
  src/test/java/plugins/ExternalWorkspaceManagerPluginTest.java
Labels: internal

#1187 replace reflection with pid
  src/main/java/org/jenkinsci/test/acceptance/controller/LocalController.java
Labels: chore

#1200 Migrate from `javax.inject` to `jakarta.inject`
  pom.xml
  src/main/java/org/jenkinsci/test/acceptance/FallbackConfig.java
  src/main/java/org/jenkinsci/test/acceptance/controller/ExistingJenkinsController.java
  src/main/java/org/jenkinsci/test/acceptance/controller/JBossController.java
  src/main/java/org/jenkinsci/test/acceptance/controller/JenkinsController.java
  src/main/java/org/jenkinsci/test/acceptance/controller/LocalController.java
  src/main/java/org/jenkinsci/test/acceptance/controller/TomcatController.java
  src/main/java/org/jenkinsci/test/acceptance/controller/WinstoneController.java
  src/main/java/org/jenkinsci/test/acceptance/docker/DockerContainerHolder.java
  src/main/java/org/jenkinsci/test/acceptance/guice/TestName.java
  src/main/java/org/jenkinsci/test/acceptance/guice/World.java
  src/main/java/org/jenkinsci/test/acceptance/guice/WorldCleaner.java
  src/main/java/org/jenkinsci/test/acceptance/junit/AbstractJUnitTest.java
  src/main/java/org/jenkinsci/test/acceptance/junit/DiagnosticRule.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/jabber/JabberGlobalConfig.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/jira/JiraGlobalConfig.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/mailer/MailerGlobalConfig.java
  src/main/java/org/jenkinsci/test/acceptance/po/CapybaraPortingLayerImpl.java
  src/main/java/org/jenkinsci/test/acceptance/po/Job.java
  src/main/java/org/jenkinsci/test/acceptance/po/PageObject.java
  src/main/java/org/jenkinsci/test/acceptance/po/PluginManager.java
  src/main/java/org/jenkinsci/test/acceptance/recorder/HarRecorder.java
  src/main/java/org/jenkinsci/test/acceptance/recorder/TestRecorderRule.java
  src/main/java/org/jenkinsci/test/acceptance/server/JenkinsControllerPoolProcess.java
  src/main/java/org/jenkinsci/test/acceptance/server/PooledJenkinsController.java
  src/main/java/org/jenkinsci/test/acceptance/slave/LocalSlaveProvider.java
  src/main/java/org/jenkinsci/test/acceptance/slave/SlaveProvider.java
  src/main/java/org/jenkinsci/test/acceptance/update_center/CachedUpdateCenterMetadataLoader.java
  src/main/java/org/jenkinsci/test/acceptance/utils/aether/AetherModule.java
  src/main/java/org/jenkinsci/test/acceptance/utils/aether/ArtifactResolverUtil.java
  src/test/java/plugins/DashboardViewPluginTest.java
  src/test/java/plugins/DeclarativePipelineTest.java
  src/test/java/plugins/DeployPluginTest.java
  src/test/java/plugins/GerritTriggerTest.java
  src/test/java/plugins/GitPluginTest.java
  src/test/java/plugins/LdapPluginTest.java
  src/test/java/plugins/WorkflowPluginTest.java
Labels: internal
