Repository jenkinsci/acceptance-test-harness, pull requests merged in 2023-10, with the labels that each got.

#1390 Switch to production build of JDK 21
  src/main/resources/ath-container/Dockerfile
Labels: tests

#1394 fix folders tests
  src/main/java/org/jenkinsci/test/acceptance/po/Folder.java
Labels: bug

#1396 Update LTS in Maven profile to 2.414.3
  pom.xml
Labels: dependencies
