Repository jenkinsci/acceptance-test-harness, pull requests merged in 2023-03, with the labels that each got.

#1043 Use older 108 version of firefox in ath-container
  src/main/resources/ath-container/Dockerfile
  src/main/resources/ath-container/run.sh
  src/test/java/plugins/OwnershipPluginTest.java
Labels: bug

#1048 Fix hadolint errors
  src/main/resources/ath-container/Dockerfile
Labels: chore

#973 Upgrade to Selenium 4
  .github/dependabot.yml
  docs/BROWSER.md
  pom.xml
  src/main/java/org/jenkinsci/test/acceptance/FallbackConfig.java
  src/main/java/org/jenkinsci/test/acceptance/junit/Wait.java
  src/main/java/org/jenkinsci/test/acceptance/utils/SauceLabsConnection.java
  vars.cmd
Labels: dependencies, chore, breaking

#1069 Add URL to pom.xml
  pom.xml
Labels: chore

#1063 Fix tomcat 10 dependabot path
  .github/dependabot.yml
Labels: chore

#1070 Update maven to 3.9.1
  src/main/resources/ath-container/Dockerfile
Labels: dependencies

#1061 Bump jffi from 1.3.10 to 1.3.11
  pom.xml
Labels: dependencies

#1066 [#1053] Add tests for Ant Plugin
  src/main/java/org/jenkinsci/test/acceptance/docker/fixtures/SshAgentContainer.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/ant/AntInstallation.java
  src/test/java/plugins/AntPluginTest.java
  src/test/resources/plugins/ant/custom-build-file.xml
Labels: enhancement

#1084 Pipeline test utility classes needed for multiple contributions
  src/main/java/org/jenkinsci/test/acceptance/AbstractPipelineTest.java
  src/main/java/org/jenkinsci/test/acceptance/utils/PipelineTestUtils.java
Labels: enhancement
