Repository jenkinsci/acceptance-test-harness, pull requests merged in 2023-09, with the labels that each got.

#1352 chore(jenkinsfile): use spot instance for the first try or falls back to on-demand
  Jenkinsfile
Labels: chore

#1351 Remove unnecessary version number and exclusion
  pom.xml
Labels: skip-changelog

#1335 Gitlab container and tests
  .github/dependabot.yml
  .github/renovate.json
  pom.xml
  src/main/java/org/jenkinsci/test/acceptance/docker/fixtures/GitLabContainer.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/gitlab_plugin/GitLabBranchSource.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/gitlab_plugin/GitLabOrganizationFolder.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/gitlab_plugin/GitLabPersonalAccessTokenCredential.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/gitlab_plugin/GitLabServerConfig.java
  src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/GitLabContainer/Dockerfile
  src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/GitLabContainer/create_user.rb
  src/test/java/plugins/GitLabPluginTest.java
Labels: enhancement, tests
