Repository jenkinsci/acceptance-test-harness, pull requests merged in 2023-12, with the labels that each got.

#1445 Suppress known failures
  src/test/java/plugins/GroovyPluginTest.java
  src/test/java/plugins/JobDslPluginTest.java
  src/test/java/plugins/ScriptSecurityPluginTest.java
Labels: chore

#1446 Forward compatibility for use Jenkins modal for 'Apply' button failures
  src/test/java/core/FreestyleJobTest.java
  src/test/java/plugins/ScriptSecurityPluginTest.java
Labels: enhancement

#1440 Feat: Update LTS Jenkins version in pom.xml for 2.426.2 release
  pom.xml
Labels: dependencies
