Repository jenkinsci/acceptance-test-harness, pull requests merged in 2024-05, with the labels that each got.

#1547 Work around JENKINS-73034 and JENKINS-73168
  src/test/java/core/CreateItemTest.java
  src/test/java/core/FreestyleJobTest.java
Labels: skip-changelog

#1533 Update LTS in Maven profile to 2.452.1
  pom.xml
Labels: enhancement

#1569 Remove `WorkflowPluginTest#sshGitInsideDocker`
  .github/dependabot.yml
  src/main/java/org/jenkinsci/test/acceptance/docker/fixtures/DockerAgentContainer.java
  src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/DockerAgentContainer/Dockerfile
  src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/DockerAgentContainer/entrypoint.sh
  src/test/java/plugins/WorkflowPluginTest.java
Labels: removed

#1567 Upgrade test containers to Ubuntu 24.04 and Java 17
  .github/dependabot.yml
  Jenkinsfile
  ath-container.sh
  pom.xml
  src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/GitContainer/Dockerfile
  src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/JiraContainer/Dockerfile
  src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/SshAgentContainer/Dockerfile
  src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/Tomcat10Container/Dockerfile
  src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/XvncSlaveContainer/Dockerfile
  src/test/java/plugins/AntPluginTest.java
  src/test/java/plugins/SshSlavesPluginTest.java
Labels: chore

#1557 Forward compatibility for build history widget rewrite
  src/test/java/plugins/DescriptionSetterPluginTest.java
  src/test/java/plugins/NodeLabelParameterPluginTest.java
Labels: enhancement
