Repository jenkinsci/acceptance-test-harness, pull requests merged in 2024-11, with the labels that each got.

#1824 Enable automerge for renovate PRs
  .github/renovate.json
Labels: chore

#1818 Remove workaround for JENKINS-73900 in `CspRule`
  src/main/java/org/jenkinsci/test/acceptance/junit/CspRule.java
Labels: tests

#1840 Add workaround for JENKINS-74890 in `CspRule`
  src/main/java/org/jenkinsci/test/acceptance/junit/CspRule.java
Labels: skip-changelog

#1839 Adapt to new CSP design
  src/main/java/org/jenkinsci/test/acceptance/junit/CspRule.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/csp/ContentSecurityPolicyReport.java
Labels: internal

#1846 Remove JENKINS-74890 workaround
  src/main/java/org/jenkinsci/test/acceptance/junit/CspRule.java
Labels: tests

#1847 Fix Scriptler tests
  src/main/java/org/jenkinsci/test/acceptance/plugins/scriptler/Script.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/scriptler/ScriptResult.java
Labels: tests
