Repository jenkinsci/acceptance-test-harness, pull requests merged in 2024-10, with the labels that each got.

#1756 Forward compatibility with jenkinsci/credentials-plugin#551
  src/main/java/org/jenkinsci/test/acceptance/plugins/ssh_slaves/SshSlaveLauncher.java
Labels: enhancement

#1755 Use 2.462.3 in LTS profile
  pom.xml
Labels: chore

#1763 Format `renovate.json`
  .github/renovate.json
Labels: skip-changelog

#1764 Migrate `renovate.json`
  .github/renovate.json
Labels: skip-changelog

#1762 Adjust to jenkinsci-matrix-project-plugin#213
  src/main/java/org/jenkinsci/test/acceptance/po/LabelAxis.java
Labels: enhancement

#1773 Upgrade to 2.480
  pom.xml
  src/main/java/org/jenkinsci/test/acceptance/plugins/ssh_slaves/SshSlaveLauncher.java
Labels: enhancement

#1754 Avoid depending on labels, rather use the button name
  src/main/java/org/jenkinsci/test/acceptance/po/ConfigurablePageObject.java
  src/main/java/org/jenkinsci/test/acceptance/po/View.java
Labels: enhancement

#1784 Remove Matrix Reloaded from ATH
  src/main/java/org/jenkinsci/test/acceptance/plugins/matrix_reloaded/MatrixReloadedAction.java
  src/test/java/plugins/MatrixPluginTest.java
  src/test/java/plugins/MatrixReloadedPluginTest.java
Labels: removed

#1804 Adapt to dialog changes in matrix-auth 3.2.3
  src/main/java/org/jenkinsci/test/acceptance/plugins/matrix_auth/MatrixAuthorizationStrategy.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/matrix_auth/ProjectMatrixProperty.java
  src/main/java/org/jenkinsci/test/acceptance/po/CapybaraPortingLayerImpl.java
Labels: tests, developer

#1805 [JENKINS-74005] Obtaining login button via href instead of text
  src/test/java/plugins/OicAuthPluginTest.java
Labels: tests

#1743 Run ATH with CSP
  Jenkinsfile
  src/main/java/org/jenkinsci/test/acceptance/junit/CspRule.java
  src/main/java/org/jenkinsci/test/acceptance/po/GlobalSecurityConfig.java
Labels: enhancement

#1749 Enforce that there are no CSP violations when `csp.rule` is defined
  src/main/java/org/jenkinsci/test/acceptance/junit/CspRule.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/csp/ContentSecurityPolicyReport.java
  src/test/java/core/PublisherOrderTest.java
  src/test/java/plugins/ArtifactoryPluginTest.java
  src/test/java/plugins/JobDslPluginTest.java
  src/test/java/plugins/MailerPluginTest.java
  src/test/java/plugins/MatrixAuthPluginTest.java
  src/test/java/plugins/PlainCredentialsBindingTest.java
  src/test/java/plugins/ScriptSecurityPluginTest.java
  src/test/java/plugins/SshSlavesPluginTest.java
Labels: enhancement

#1814 Use Jenkins 2.479.1 in LTS profile
  pom.xml
Labels: chore
