Repository jenkinsci/acceptance-test-harness, pull requests merged in 2024-03, with the labels that each got.

#1497 Update selectors: credentials dialog, declarative migration assistant
  src/main/java/org/jenkinsci/test/acceptance/plugins/credentials/Credential.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/ssh_credentials/SshCredentialDialog.java
  src/test/java/plugins/DeclarativeAssistantMigrationTest.java
Labels: bug

#1492 Add a page object for the snippet generator
  src/main/java/org/jenkinsci/test/acceptance/po/JenkinsConfig.java
  src/main/java/org/jenkinsci/test/acceptance/po/SnippetGenerator.java
  src/test/java/org/jenkinsci/test/acceptance/po/SnippetGeneratorTest.java
Labels: enhancement

#1501 Validate Gradle wrapper
  .github/workflows/verify-gradle-wrapper.yaml
Labels: chore
