Repository jenkinsci/acceptance-test-harness, pull requests merged in 2024-09, with the labels that each got.

#1706 Cleanup the docker permission issues.
  Jenkinsfile
  ath-container.sh
  src/main/resources/ath-container/Dockerfile
Labels: build-image

#1708 Add `.git-blame-ignore-revs`
  .git-blame-ignore-revs
Labels: skip-changelog

#1710 Clean up usage of third-party libraries
  src/main/java/org/jenkinsci/test/acceptance/controller/JBossController.java
  src/main/java/org/jenkinsci/test/acceptance/controller/JenkinsLogWatcher.java
  src/main/java/org/jenkinsci/test/acceptance/controller/LocalController.java
  src/main/java/org/jenkinsci/test/acceptance/controller/TomcatController.java
  src/main/java/org/jenkinsci/test/acceptance/controller/WinstoneController.java
  src/main/java/org/jenkinsci/test/acceptance/junit/FailureDiagnostics.java
  src/main/java/org/jenkinsci/test/acceptance/junit/Wait.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/docker_build_step/DockerCommand.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/mock_security_realm/MockSecurityRealm.java
  src/main/java/org/jenkinsci/test/acceptance/po/CapybaraPortingLayerImpl.java
  src/main/java/org/jenkinsci/test/acceptance/po/Jenkins.java
  src/main/java/org/jenkinsci/test/acceptance/po/PageObject.java
  src/main/java/org/jenkinsci/test/acceptance/po/ToolInstallation.java
  src/main/java/org/jenkinsci/test/acceptance/po/WizardLogin.java
  src/test/java/plugins/AuthorizeProjectTest.java
  src/test/java/plugins/GerritTriggerTest.java
  src/test/java/plugins/JabberPluginTest.java
Labels: internal

#1701 Add oic auth e2e
  .github/renovate.json
  docs/BROWSER.md
  docs/DOCKER.md
  pom.xml
  src/main/java/org/jenkinsci/test/acceptance/po/OicAuthSecurityRealm.java
  src/main/java/org/jenkinsci/test/acceptance/po/WhoAmI.java
  src/main/java/org/jenkinsci/test/acceptance/utils/keycloack/KeycloakUtils.java
  src/test/java/plugins/OicAuthPluginTest.java
  vars.cmd
Labels: enhancement

#1719 Partially revert commit 4979b2e1652e846cb505cf13b0f628457e47cd18
  src/main/java/org/jenkinsci/test/acceptance/utils/IOUtil.java
Labels: bug

#1729 Upgrade Maven from 3.8.1 to 3.9.6
  pom.xml
  src/main/java/org/jenkinsci/test/acceptance/utils/aether/AetherModule.java
Labels: dependencies, java

#1733 Migrate from deprecated `org.eclipse.aether.impl.guice.AetherModule` to Sisu
  .github/renovate.json
  pom.xml
  src/main/java/org/jenkinsci/test/acceptance/utils/aether/AetherModule.java
Labels: enhancement
