Repository jenkinsci/acceptance-test-harness, pull requests merged in 2024-08, with the labels that each got.

#1662 chore(pipeline) stop using Docker login primitive - reverts #1634 and #1640
  Jenkinsfile
Labels: chore

#1648 Upgrade Firefox from 123.x to 129.x
  src/main/resources/ath-container/Dockerfile
Labels: developer, build-image

#1674 Use SLF4J BOM
  pom.xml
Labels: dependencies, java

#1676 Upgrade Firefox to 129.0.1
  src/main/resources/ath-container/Dockerfile
Labels: dependencies, build-image

#1687 Unpin plugin versions
  src/test/java/core/CredentialsTest.java
  src/test/java/plugins/ActiveDirectoryTest.java
  src/test/java/plugins/CredentialsBindingTest.java
  src/test/java/plugins/DeclarativeAssistantMigrationTest.java
  src/test/java/plugins/DisplayUrlApiTest.java
  src/test/java/plugins/JobDslPluginTest.java
  src/test/java/plugins/LdapPluginTest.java
  src/test/java/plugins/MailWatcherPluginTest.java
  src/test/java/plugins/MatrixAuthPluginTest.java
  src/test/java/plugins/PlainCredentialsBindingTest.java
  src/test/java/plugins/SSHCredentialsTest.java
  src/test/java/plugins/SshSlavesPluginTest.java
  src/test/java/plugins/StageViewTest.java
  src/test/java/plugins/SubversionPluginTest.java
  src/test/java/plugins/WorkflowMultibranchTest.java
  src/test/java/plugins/WorkflowPluginTest.java
  src/test/java/plugins/XvncPluginTest.java
Labels: tests

#1689 Re-enable category
  src/test/java/core/JenkinsDatabaseSecurityRealmTest.java
Labels: tests

#1690 Remove dead code for obsolete versions
  src/main/java/org/jenkinsci/test/acceptance/AbstractPipelineTest.java
  src/main/java/org/jenkinsci/test/acceptance/Matchers.java
  src/main/java/org/jenkinsci/test/acceptance/controller/LocalController.java
  src/main/java/org/jenkinsci/test/acceptance/controller/WinstoneController.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/audit_trail/AuditTrailLogger.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/build_timeout/BuildTimeout.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/config_file_provider/CustomConfig.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/credentials/DomainPage.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/dashboard_view/read/ProjectStatusStdJobList.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/email_ext/EmailExtPublisher.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/email_ext/GlobalConfig.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/git/GitScm.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/gradle/GradleStep.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/jira/JiraGlobalConfig.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/logparser/LogParserGlobalConfig.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/maven/MavenBuildStep.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/ssh_credentials/SshPrivateKeyCredential.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/subversion/SubversionScm.java
  src/main/java/org/jenkinsci/test/acceptance/po/FormValidation.java
  src/main/java/org/jenkinsci/test/acceptance/po/GlobalSecurityConfig.java
  src/main/java/org/jenkinsci/test/acceptance/po/Jenkins.java
  src/main/java/org/jenkinsci/test/acceptance/po/JenkinsDatabaseSecurityRealm.java
  src/main/java/org/jenkinsci/test/acceptance/po/JenkinsLogger.java
  src/main/java/org/jenkinsci/test/acceptance/po/Job.java
  src/main/java/org/jenkinsci/test/acceptance/po/JobsMixIn.java
  src/main/java/org/jenkinsci/test/acceptance/po/LdapSecurityRealm.java
  src/main/java/org/jenkinsci/test/acceptance/po/LdapSecurityRealm_Pre1_10.java
  src/main/java/org/jenkinsci/test/acceptance/po/PasswordParameter.java
  src/main/java/org/jenkinsci/test/acceptance/po/SlavesMixIn.java
  src/main/java/org/jenkinsci/test/acceptance/po/ToolInstallation.java
  src/main/java/org/jenkinsci/test/acceptance/po/TopLevelItem.java
  src/main/java/org/jenkinsci/test/acceptance/po/ViewsMixIn.java
  src/test/java/core/FreestyleJobTest.java
  src/test/java/core/InstallWizardTest.java
  src/test/java/core/PluginManagerTest.java
  src/test/java/plugins/JavadocPluginTest.java
  src/test/java/plugins/MatrixPluginTest.java
  src/test/java/plugins/SshSlavesPluginTest.java
  src/test/java/plugins/WorkflowMultibranchTest.java
Labels: tests

#1694 Adapt to Apache Maven Javadoc Plugin 3.10.0
  src/test/java/plugins/JavadocPluginTest.java
  src/test/java/plugins/PipelineTest.java
Labels: bug

#1693 Remove more dead code
  src/main/java/org/jenkinsci/test/acceptance/plugins/build_timeout/BuildTimeout.java
  src/main/java/org/jenkinsci/test/acceptance/po/PluginManager.java
  src/main/java/org/jenkinsci/test/acceptance/po/User.java
  src/main/java/org/jenkinsci/test/acceptance/po/View.java
  src/main/java/org/jenkinsci/test/acceptance/po/WorkflowJob.java
  src/test/java/plugins/JobDslPluginTest.java
Labels: skip-changelog
