Repository jenkinsci/acceptance-test-harness, pull requests merged in 2024-07, with the labels that each got.

#1584 Compatibility with 'Categorize the user properties'
  src/main/java/org/jenkinsci/test/acceptance/po/User.java
Labels: enhancement

#1620 Fix SnippetGeneratorTest
  src/main/java/org/jenkinsci/test/acceptance/po/SnippetGenerator.java
Labels: bug

#1618 chore: update lts in maven profile to 2.452.3
  .gitignore
  pom.xml
Labels: enhancement

#1635 Upgrade Ubuntu from 22.04 to 24.04
  Jenkinsfile
  README.md
  src/main/resources/ath-container/Dockerfile
  src/main/resources/ath-container/set-java.sh
Labels: enhancement, build-image

#1638 Update `geckodriver` URL
  src/main/resources/ath-container/Dockerfile
Labels: internal

#1637 Upgrade Firefox from 108.0.2 to 123.0.1
  src/main/resources/ath-container/Dockerfile
Labels: enhancement, build-image

#1643 Install Firefox from `packages.mozilla.org`
  src/main/resources/ath-container/Dockerfile
Labels: developer, build-image

#1644 Install packages at beginning of Docker build
  .github/renovate.json
  src/main/resources/ath-container/Dockerfile
Labels: developer, build-image

#1645 Clean up Docker image
  ath-container.sh
  src/main/resources/ath-container/Dockerfile
Labels: developer, build-image

#1651 Revert UID/GID changes from #1645
  ath-container.sh
  src/main/resources/ath-container/Dockerfile
Labels: bug

#1652 Replace Dependabot with Renovate
  .github/dependabot.yml
  .github/renovate.json
Labels: skip-changelog

#1654 More Renovate tweaks
  .github/renovate.json
  src/main/resources/ath-container/Dockerfile
  src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/GitContainer/Dockerfile
  src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/JavaGitContainer/Dockerfile
  src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/JiraContainer/Dockerfile
  src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/Tomcat10Container/Dockerfile
Labels: skip-changelog

#1657 Add support for Firefox 129 or newer
  src/main/java/org/jenkinsci/test/acceptance/FallbackConfig.java
  src/test/java/core/FormValidationTest.java
Labels: enhancement

#1659 more
  .github/renovate.json
Labels: skip-changelog
