Repository jenkinsci/acceptance-test-harness, pull requests merged in 2025-05, with the labels that each got.

#1988 Use consistent Windows detection conditional
  src/main/java/org/jenkinsci/test/acceptance/FallbackConfig.java
Labels: internal

#1992 Support BiDi in `RemoteWebDriver`
  src/main/java/org/jenkinsci/test/acceptance/FallbackConfig.java
Labels: bug

#1995 `surefire.runOrder=alphabetical` for reproducibility
  pom.xml
Labels: internal

#1996 Port `vars.cmd` to Unix
  vars.sh
Labels: internal

#1985 Remove workaround added in #457
  src/main/java/org/jenkinsci/test/acceptance/FallbackConfig.java
Labels: bug

#1999 Disable HAR recording by default
  src/main/java/org/jenkinsci/test/acceptance/recorder/HarRecorder.java
Labels: bug

#2012 Stop using outdated `-debug` images in documentation
  docs/BROWSER.md
Labels: documentation

#2014 Use consistent screen dimensions
  src/main/java/org/jenkinsci/test/acceptance/FallbackConfig.java
  vars.cmd
  vars.sh
Labels: internal

#2013 Automatically update `vars.sh` with Renovate
  .github/renovate.json
Labels: skip-changelog

#2015 Remove cobertura-plugin tests as it is EOL
  src/main/java/org/jenkinsci/test/acceptance/plugins/cobertura/CoberturaAction.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/cobertura/CoberturaPublisher.java
  src/test/java/plugins/CoberturaPluginTest.java
  src/test/resources/cobertura_plugin/coverage.xml
Labels: removed

#2016 Fix `UselessFileDetectorReplacement`
  src/main/java/org/jenkinsci/test/acceptance/plugins/audit_trail/AuditTrailLogger.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/logparser/LogParserGlobalConfig.java
  src/main/java/org/jenkinsci/test/acceptance/selenium/UselessFileDetectorReplacement.java
Labels: bug

#2010 Remove Firefox from image; run with Docker Selenium image and Docker Compose
  .github/renovate.json
  Jenkinsfile
  ath-container.sh
  build-image.sh
  ci.sh
  docker-compose.yml
  docs/BROWSER.md
  docs/DOCKER.md
  pom.xml
  run.sh
  set-java.sh
  src/main/java/org/jenkinsci/test/acceptance/FallbackConfig.java
  src/main/resources/ath-container/Dockerfile
  src/main/resources/ath-container/run.sh
  src/main/resources/ath-container/set-java.sh
  src/main/resources/ath-container/vnc.sh
  vnc.sh
Labels: enhancement

#2022 Record videos with Selenium instead of Monte
  ci.sh
  docker-compose.yml
  src/main/java/org/jenkinsci/test/acceptance/FallbackConfig.java
  src/main/java/org/jenkinsci/test/acceptance/recorder/TestRecorderRule.java
  src/test/java/org/jenkinsci/test/acceptance/recorder/TestRecorderRuleTest.java
Labels: enhancement

#2026 Clean up Chrome support in `FallbackConfig`
  src/main/java/org/jenkinsci/test/acceptance/FallbackConfig.java
Labels: enhancement

#2029 Fix Docker build warnings
  src/main/resources/ath-container/Dockerfile
Labels: internal

#2028 Verify Maven checksum
  src/main/resources/ath-container/Dockerfile
Labels: internal

#2032 Support Fedora Linux
  ath-container.sh
  build-image.sh
  ci.sh
  docker-compose.yml
  src/main/java/org/jenkinsci/test/acceptance/plugins/logparser/LogParserPublisher.java
  src/test/java/plugins/ConfigurationAsCodeTest.java
Labels: enhancement
