Repository jenkinsci/acceptance-test-harness, pull requests merged in 2025-04, with the labels that each got.

#1930 chore(maven): Use Jenkins 2.492.2 in LTS profile.
  pom.xml
Labels: dependencies

#1936 Remove JabberPluginTest that has been ignored for over 10 years
  .github/renovate.json
  src/main/java/org/jenkinsci/test/acceptance/docker/fixtures/JabberContainer.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/jabber/JabberGlobalConfig.java
  src/main/java/org/jenkinsci/test/acceptance/plugins/jabber/JabberPublisher.java
  src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/JabberContainer/Dockerfile
  src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/JabberContainer/supervisord.conf
  src/test/java/plugins/JabberPluginTest.java
Labels: developer

#1955 Upgrade MonteMedia from 17.1 to 17.2.1
  pom.xml
  src/main/java/org/jenkinsci/test/acceptance/recorder/TestRecorderRule.java
  src/main/resources/META-INF/services/org.monte.media.av.CodecSpi
  src/main/resources/META-INF/services/org.monte.media.av.MovieReaderSpi
  src/main/resources/META-INF/services/org.monte.media.av.MovieWriterSpi
Labels: dependencies, java

#1917 Forward compatibility for Redesign the Jenkins header
  src/test/java/core/FormValidationTest.java
  src/test/java/core/PublisherOrderTest.java
  src/test/java/plugins/ArtifactoryPluginTest.java
  src/test/java/plugins/DashboardViewPluginTest.java
  src/test/java/plugins/MailerPluginTest.java
  src/test/java/plugins/PlainCredentialsBindingTest.java
  src/test/java/plugins/SshSlavesPluginTest.java
Labels: developer

#1984 Clean up `beforeunload` user prompt handling
  src/main/java/org/jenkinsci/test/acceptance/FallbackConfig.java
  src/main/java/org/jenkinsci/test/acceptance/junit/CspRule.java
  src/main/java/org/jenkinsci/test/acceptance/po/CapybaraPortingLayerImpl.java
  src/test/java/core/FormValidationTest.java
  src/test/java/core/PublisherOrderTest.java
  src/test/java/plugins/ArtifactoryPluginTest.java
  src/test/java/plugins/MailerPluginTest.java
  src/test/java/plugins/PlainCredentialsBindingTest.java
  src/test/java/plugins/SshSlavesPluginTest.java
Labels: bug
