Repository jenkinsci/acceptance-test-harness, pull requests merged in 2025-09, with the labels that each got.

#2151 Remove Groovy configuration injection support
  dockerinject.groovy
  docs/FIXTURES.md
  docs/SINGLE-TEST.md
  pom.xml
  single-plugin.groovy
  src/main/java/org/jenkinsci/test/acceptance/Config.java
  src/main/java/org/jenkinsci/test/acceptance/guice/AdditionalBinderDsl.java
  src/main/java/org/jenkinsci/test/acceptance/guice/World.java
  vars.cmd
  vars.sh
Labels: removed

#2162 Rename `FallbackConfig` to `Config`
  docs/BROWSER.md
  src/main/java/org/jenkinsci/test/acceptance/Config.java
  src/main/java/org/jenkinsci/test/acceptance/FallbackConfig.java
  src/main/java/org/jenkinsci/test/acceptance/guice/World.java
  src/main/java/org/jenkinsci/test/acceptance/po/PluginManager.java
  src/main/java/org/jenkinsci/test/acceptance/server/JenkinsControllerPoolProcess.java
Labels: breaking

#2170 Increase timeout on ant plugin tests
  src/test/java/plugins/AntPluginTest.java
Labels: bug

#2169 adjust vars.cmd so it is also updated by renovate
  .github/renovate.json
  vars.cmd
Labels: developer
