Repository jenkinsci/acceptance-test-harness, pull requests merged in 2025-06, with the labels that each got.

#2040 Fix build caching
  docker-compose.yml
Labels: bug

#2057 Disable password manager leak detection in Chrome
  src/main/java/org/jenkinsci/test/acceptance/FallbackConfig.java
Labels: bug

#2061 [JENKINS-75797] Update test following email-ext plugin refactoring
  src/main/java/org/jenkinsci/test/acceptance/plugins/email_ext/EmailExtPublisher.java
Labels: enhancement

#2027 Remove Monte
  pom.xml
  src/main/java/org/jenkinsci/test/acceptance/FallbackConfig.java
  src/main/java/org/jenkinsci/test/acceptance/recorder/JUnitScreenRecorder.java
  src/main/java/org/jenkinsci/test/acceptance/recorder/TestRecorderRule.java
  src/test/java/org/jenkinsci/test/acceptance/recorder/TestRecorderRuleTest.java
Labels: removed

#1932 Forward compatibility for jenkinsci/jenkins#10432
  src/main/java/org/jenkinsci/test/acceptance/po/Job.java
Labels: internal
